import Link from 'next/link';
import { Badge } from '../../../components/ui/badge';
import type { WaterfallAdvisory, AdvisoryRisk } from '../../../lib/advisory/advisory-engine';

function severityTone(severity: AdvisoryRisk['severity']): 'neutral' | 'green' | 'warm' {
  if (severity === 'high') return 'warm';
  if (severity === 'attention') return 'warm';
  return 'neutral';
}

function AdvisoryDisclaimer({ text }: { text: string }) {
  return (
    <p className="small-note" style={{ marginTop: 12 }}>
      <Badge tone="neutral">Advisory only</Badge> {text}
    </p>
  );
}

/** Full advisory, used by the /ai workspace. Prose, references, risks, questions. */
export function AdvisoryFull({ advisory }: { advisory: WaterfallAdvisory }) {
  return (
    <div className="stack">
      <section className="card">
        <p className="eyebrow">Advisory headline</p>
        <h2>{advisory.headline}</h2>
        <p className="small-note">Generated by {advisory.provider} · advisory only, no official figures produced.</p>
        <AdvisoryDisclaimer text={advisory.disclaimer} />
      </section>

      {advisory.narrative.map((section, index) => (
        <section className="card" key={index}>
          <div className="split-row">
            <div><p className="eyebrow">Explanation</p><h2>{section.heading}</h2></div>
          </div>
          {section.paragraphs.map((paragraph, pIndex) => <p key={pIndex}>{paragraph}</p>)}
          {section.references.length > 0 ? (
            <div className="table-wrap">
              <table>
                <thead><tr><th>Referenced figure</th><th>Value (from locked records)</th></tr></thead>
                <tbody>
                  {section.references.map((reference, rIndex) => (
                    <tr key={rIndex}><td>{reference.label}</td><td>{reference.value}</td></tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : null}
        </section>
      ))}

      <section className="card">
        <div className="split-row">
          <div><p className="eyebrow">Advisory flags</p><h2>Risks &amp; things to watch</h2></div>
        </div>
        <div className="table-wrap">
          <table>
            <thead><tr><th>Severity</th><th>Flag</th><th>Detail</th></tr></thead>
            <tbody>
              {advisory.risks.map((risk, index) => (
                <tr key={index}>
                  <td><Badge tone={severityTone(risk.severity)}>{risk.severity}</Badge></td>
                  <td><strong>{risk.title}</strong></td>
                  <td>{risk.detail}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="card">
        <div className="split-row">
          <div><p className="eyebrow">Suggested questions</p><h2>Questions worth asking</h2></div>
        </div>
        <div className="table-wrap">
          <table>
            <thead><tr><th>Question</th><th>Why it matters</th></tr></thead>
            <tbody>
              {advisory.suggestedQuestions.map((item, index) => (
                <tr key={index}><td>{item.question}</td><td className="small-note">{item.rationale}</td></tr>
              ))}
            </tbody>
          </table>
        </div>
        <AdvisoryDisclaimer text={advisory.disclaimer} />
      </section>
    </div>
  );
}

/** Compact advisory, embedded read-only in the waterfall detail page. */
export function AdvisoryCompact({ advisory, varianceReportId }: { advisory: WaterfallAdvisory; varianceReportId: string }) {
  const topRisks = advisory.risks.slice(0, 2);
  return (
    <section className="card">
      <div className="split-row">
        <div><p className="eyebrow">Planning Advisor (read-only)</p><h2>Plain-language explanation</h2></div>
        <Badge tone="neutral">Advisory only</Badge>
      </div>
      <p>{advisory.headline}</p>
      {advisory.narrative[0] ? <p className="small-note">{advisory.narrative[0].paragraphs[0]}</p> : null}
      {topRisks.length > 0 ? (
        <ul className="small-note">
          {topRisks.map((risk, index) => <li key={index}><strong>{risk.title}:</strong> {risk.detail}</li>)}
        </ul>
      ) : null}
      <p className="small-note">{advisory.disclaimer}</p>
      <p><Link className="button button-secondary button-link" href={`/ai/${varianceReportId}`}>Open full advisory</Link></p>
    </section>
  );
}
